name: build
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [Win32, x64]
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: megasource
    - name: Checkout LÖVE
      uses: actions/checkout@v4
      with:
        path: megasource/libs/love
        repository: love2d/love
        ref: 12.0-development
    - name: Remove Strawbery Perl From Path
      run: |
        move /y C:\Strawberry C:\Strawberry_not_in_PATH
        exit /b 0
    - name: Configure
      env:
        PLATFORM: ${{ matrix.platform }}
      run: cmake -Bbuild -Hmegasource -T v142 -A %PLATFORM% -DCMAKE_INSTALL_PREFIX=%CD%\install
    - name: Install
      run: cmake --build build --config Release --target install -j2
